wifi_ssid: "Your Wifi SSID Goes Here"
wifi_password: "some_cool_password_42"
wifi_fallback_password: "this_is_a_wifi_fallback_password_1111"
# Generate a 32-bit encryption key and encode in base64
# On Linux: head -c 32 /dev/random | base64
encryption_key: "replace_with_32_bit_base64_key"
# OTA password. Replace with a strong password.
ota_password: 'i4cVckXmJxln'
